name: Databricks CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  validate-dev:
    name: Validate DAB (DEV)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Configure Databricks Auth
        run: |
          mkdir -p ~/.databricks
          cat > ~/.databrickscfg <<EOF
          [DEFAULT]
          host = ${{ secrets.DATABRICKS_HOST }}
          token = ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      - name: Validate Bundle
        run: |
          databricks bundle validate -t dev

  deploy-qa:
    name: Deploy QA
    runs-on: ubuntu-latest
    needs: validate-dev

    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Configure Databricks Auth
        run: |
          mkdir -p ~/.databricks
          cat > ~/.databrickscfg <<EOF
          [DEFAULT]
          host = ${{ secrets.DATABRICKS_HOST }}
          token = ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      - name: Deploy QA
        run: |
          databricks bundle deploy -t qa